//! Store type, connection setup, and scope-filter SQL helpers.

use std::path::{Path, PathBuf};

use rusqlite::Connection;

use crate::error::Error;
use crate::log::{ROTATED_LOG_SERIES, finalize_pending_rotations, maybe_rotate_log};
use crate::seed::seed_ontology;
use crate::types::ScopeWalk;

// Embedded migrations applied in order on every `Store::open`.
// Each `CREATE` is `IF NOT EXISTS` so re-application is a no-op (ADR-0005).
// `MIGRATIONS` is generated by `build.rs` from the workspace `migrations/`
// directory; add a new `NNNN_<name>.sql` file and rebuild — no code edit.
include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

// Crate-visible alias: replay applies the same embedded migrations as
// `Store::open` (the generated `MIGRATIONS` const itself is private to this
// module because `build.rs` emits it without a visibility modifier).
pub(crate) const EMBEDDED_MIGRATIONS: &[(&str, &str)] = MIGRATIONS;

/// Canonical embedding dimension for the `vec0` ANN index (ADR-0017
/// §"Dimension binding"). Bound to `nomic-embed-text`, the default model
/// returned by [`vector::VectorIndexConfig::default`]. Changing this value
/// requires a re-index — see ADR-0017 §"Dimension binding".
pub const VECTOR_INDEX_DIM: usize = 768;

/// Register the statically-linked `sqlite-vec` extension as a SQLite
/// auto-extension (ADR-0017). Called exactly once per process; subsequent
/// calls are no-ops. The auto-extension fires on every new `Connection`,
/// so all `Store::open` and `replay` paths get the `vec0` virtual-table
/// module without extra plumbing.
pub(crate) fn ensure_sqlite_vec_registered() {
    use std::sync::Once;
    static REGISTER: Once = Once::new();
    REGISTER.call_once(|| {
        // SAFETY: `sqlite3_vec_init` matches the SQLite auto-extension ABI.
        // `sqlite3_auto_extension` is process-global; the `Once` guard
        // prevents double-registration. The transmute is the idiom used by
        // the `sqlite-vec` crate's own integration test.
        unsafe {
            type RawAutoExt = unsafe extern "C" fn(
                *mut rusqlite::ffi::sqlite3,
                *mut *mut std::os::raw::c_char,
                *const rusqlite::ffi::sqlite3_api_routines,
            ) -> std::os::raw::c_int;
            rusqlite::ffi::sqlite3_auto_extension(Some(
                std::mem::transmute::<*const (), RawAutoExt>(
                    sqlite_vec::sqlite3_vec_init as *const (),
                ),
            ));
        }
    });
}

/// Local storage for Aver (ADR-0006).
///
/// Layout under `memory_dir`:
///   db.sqlite  — claims, entities, episodes, contradictions
///   log.jsonl  — append-only audit log (ADR-0005, source of truth)
pub struct Store {
    pub(crate) conn: Connection,
    pub(crate) memory_dir: PathBuf,
    pub(crate) log_path: PathBuf,
    pub(crate) event_log_path: PathBuf,
    pub(crate) observation_log_path: PathBuf,
}

/// Runtime availability of the bundled `sqlite-vec` extension (ADR-0017).
/// Static linking via the `sqlite-vec` crate makes `Available` the expected
/// state on every supported platform; the `Unavailable` variant exists so
/// sandboxed builds that disable the auto-extension can degrade gracefully
/// to the JSON full-scan recall path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SqliteVecStatus {
    Available,
    Unavailable { reason: String },
}

/// ADR-0021 §"Read-path semantics": build a SQL fragment + bound params
/// for the `scope` column under a given walk mode.
///
/// Returns `(WHERE-clause-fragment, params)`. Caller appends `AND <fragment>`
/// to its query and binds `params` in order.
pub(crate) fn scope_filter_sql(scope: &str, walk: ScopeWalk) -> (String, Vec<String>) {
    match walk {
        ScopeWalk::Any => ("1=1".to_string(), Vec::new()),
        ScopeWalk::Exact => ("scope = ?".to_string(), vec![scope.to_string()]),
        ScopeWalk::Descendants => (
            // `_` is legal in scopes (ADR-0021 charset) but is a LIKE
            // metachar: unescaped, "proj_aver" would also match rows scoped
            // "proj/aver/...". Escape metachars in the parameter and declare
            // the escape character explicitly.
            "(scope = ? OR scope LIKE ? || '/%' ESCAPE '\\')".to_string(),
            vec![scope.to_string(), escape_like_pattern(scope)],
        ),
        ScopeWalk::Ancestors => (
            // Match: row.scope is "global" (implicit root), row.scope equals
            // the input, OR the input path begins with row.scope + "/" (i.e.
            // row.scope is a strict path-prefix ancestor of the input). The
            // LIKE pattern is built from the row's own scope column, so its
            // metacharacters are escaped in SQL (same `_` hazard as above).
            "(scope = 'global' OR scope = ? OR ? LIKE (replace(replace(replace(scope, '\\', '\\\\'), '_', '\\_'), '%', '\\%') || '/%') ESCAPE '\\')"
                .to_string(),
            vec![scope.to_string(), scope.to_string()],
        ),
    }
}

/// Escape LIKE metacharacters so a scope can serve as a literal LIKE prefix
/// under `ESCAPE '\'`.
pub(crate) fn escape_like_pattern(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        if matches!(ch, '\\' | '_' | '%') {
            escaped.push('\\');
        }
        escaped.push(ch);
    }
    escaped
}

impl Store {
    /// Open or create a memory store rooted at `memory_dir`.
    /// The directory is created if it does not exist; migrations are applied.
    pub fn open(memory_dir: impl AsRef<Path>) -> Result<Self, Error> {
        // ADR-0017: register the bundled sqlite-vec extension before any
        // Connection is created so the `vec0` module is available to the
        // 0010 migration and every subsequent statement.
        ensure_sqlite_vec_registered();

        let memory_dir = memory_dir.as_ref().to_path_buf();
        std::fs::create_dir_all(&memory_dir)?;

        let db_path = memory_dir.join("db.sqlite");
        let log_path = memory_dir.join("log.jsonl");
        let event_log_path = memory_dir.join("events.jsonl");
        let observation_log_path = memory_dir.join("observations.jsonl");

        // ADR-0019 §5: rotation only at session boundaries — check at open.
        // Also recover any half-rotated `{series}.{N}.jsonl` left by a prior
        // crash. Every log series rotates, not just the claims log, so
        // events.jsonl and observations.jsonl stay bounded too.
        finalize_pending_rotations(&memory_dir)?;
        for series in ROTATED_LOG_SERIES {
            maybe_rotate_log(&memory_dir, series)?;
        }

        let conn = Connection::open(&db_path)?;
        conn.pragma_update(None, "journal_mode", "WAL")?;
        conn.pragma_update(None, "foreign_keys", "ON")?;
        // ADR-0019 §1: raise wal_autocheckpoint from 1000 to 4000 pages.
        conn.pragma_update(None, "wal_autocheckpoint", 4_000)?;
        // WAL allows one writer at a time; write paths now hold BEGIN
        // IMMEDIATE across id allocation + log append + projection insert.
        // A bounded busy timeout makes a concurrent second writer wait for
        // the first to commit instead of failing with SQLITE_BUSY.
        conn.busy_timeout(std::time::Duration::from_secs(5))?;

        // ADR-0019 §6: gate migrations on PRAGMA user_version.
        let current: i64 = conn.pragma_query_value(None, "user_version", |r| r.get(0))?;
        let target = MIGRATIONS.len() as i64;
        if current > target {
            return Err(Error::SchemaTooNew {
                found: current,
                supported: target,
            });
        }
        let start = current.max(0) as usize;
        for (_name, sql) in &MIGRATIONS[start..] {
            conn.execute_batch(sql)?;
        }
        conn.pragma_update(None, "user_version", target)?;
        seed_ontology(&conn)?;

        Ok(Self {
            conn,
            memory_dir,
            log_path,
            event_log_path,
            observation_log_path,
        })
    }

    /// Memory directory rooted at the store. Used by CLI tools (vacuum, replay).
    pub fn memory_dir(&self) -> &Path {
        &self.memory_dir
    }

    /// Read the connection-local `wal_autocheckpoint` setting. Inspection helper
    /// for ADR-0019 §1 — the pragma is per-connection and cannot be observed by
    /// reopening a fresh `Connection`.
    pub fn wal_autocheckpoint(&self) -> Result<i64, Error> {
        Ok(self
            .conn
            .pragma_query_value(None, "wal_autocheckpoint", |r| r.get(0))?)
    }

    /// Explicit close: runs `PRAGMA wal_checkpoint(TRUNCATE)` to leave no WAL
    /// behind on clean shutdown (ADR-0019 §1), then drops the connection.
    pub fn close(self) -> Result<(), Error> {
        self.conn
            .pragma_update(None, "wal_checkpoint", "TRUNCATE")?;
        drop(self.conn);
        Ok(())
    }

    /// Whether a table with the given name exists. Test/inspection helper.
    pub fn has_table(&self, name: &str) -> bool {
        self.conn
            .query_row(
                "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?1",
                [name],
                |_| Ok(()),
            )
            .is_ok()
    }

    /// Probe `sqlite-vec` capability. With the bundled crate this is
    /// expected to return `Available` everywhere; the probe is retained
    /// so callers can detect a sandboxed build where the auto-extension
    /// failed to register and fall back to the JSON recall path
    /// (ADR-0017 §"Retrieval rewrite").
    pub fn sqlite_vec_status(&self) -> Result<SqliteVecStatus, Error> {
        let available = self
            .conn
            .query_row("SELECT vec_version()", [], |_| Ok(()))
            .is_ok();
        if available {
            Ok(SqliteVecStatus::Available)
        } else {
            Ok(SqliteVecStatus::Unavailable {
                reason: "sqlite-vec extension is not loaded".to_string(),
            })
        }
    }

    /// Whether the `vec0` virtual table created by migration 0010 exists.
    /// True on every fresh `Store::open`; false only when migrations were
    /// blocked (e.g. extension missing in a sandbox build).
    pub fn vector_index_table_exists(&self) -> Result<bool, Error> {
        Ok(self.has_table("vector_index"))
    }

    /// Number of rows currently in the `vec0` ANN index. Test/inspection
    /// helper for ADR-0017's backfill correctness.
    pub fn vector_index_row_count(&self) -> Result<i64, Error> {
        Ok(self
            .conn
            .query_row("SELECT COUNT(*) FROM vector_index", [], |r| r.get(0))?)
    }
}
