use std::env;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let migrations_dir = manifest_dir
        .join("..")
        .join("..")
        .join("migrations")
        .canonicalize()
        .expect("workspace migrations directory must exist");

    println!("cargo:rerun-if-changed={}", migrations_dir.display());

    let mut entries: Vec<(u32, String, PathBuf)> = fs::read_dir(&migrations_dir)
        .expect("read migrations directory")
        .filter_map(|entry| {
            let entry = entry.expect("read migrations entry");
            let path = entry.path();
            if path.extension() != Some(OsStr::new("sql")) {
                return None;
            }
            let stem = path
                .file_stem()
                .expect("migration file has stem")
                .to_string_lossy()
                .into_owned();
            let (prefix, _) = stem.split_once('_').unwrap_or_else(|| {
                panic!("migration {stem}.sql must match NNNN_<name>.sql");
            });
            if prefix.len() != 4 || !prefix.chars().all(|c| c.is_ascii_digit()) {
                panic!("migration {stem}.sql prefix must be 4 ASCII digits");
            }
            let index: u32 = prefix
                .parse()
                .unwrap_or_else(|_| panic!("migration {stem}.sql has non-numeric prefix"));
            Some((index, stem, path))
        })
        .collect();

    entries.sort_by_key(|(index, _, _)| *index);

    for (i, (index, stem, _)) in entries.iter().enumerate() {
        let expected = (i + 1) as u32;
        if *index != expected {
            panic!(
                "migration sequence has a gap or duplicate at {stem}.sql: \
                 expected prefix {expected:04}, found {index:04}"
            );
        }
    }

    let mut generated = String::from(
        "// @generated by build.rs from workspace `migrations/` — do not edit.\n\
         const MIGRATIONS: &[(&str, &str)] = &[\n",
    );
    for (_, stem, path) in &entries {
        generated.push_str("    (\n");
        generated.push_str(&format!("        \"{stem}\",\n"));
        generated.push_str(&format!(
            "        include_str!(r\"{}\"),\n",
            absolute_str(path)
        ));
        generated.push_str("    ),\n");
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    fs::write(out_dir.join("migrations.rs"), generated).expect("write generated migrations.rs");
}

fn absolute_str(path: &Path) -> String {
    path.to_str()
        .expect("migration paths must be valid UTF-8")
        .to_string()
}
